include: package:very_good_analysis/analysis_options.yaml

linter:

  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    no_default_cases: false
    avoid_catches_without_on_clauses: false
    document_ignores: false

analyzer:
  exclude:
    - "example"
    - "test"
