name: flutter_download_manager
description: Flutter Download Manager is a Cross-Platform file downloader with resumeable, parallel and batch Download support. Also be notified of download status and progress updates
version: 0.6.0
homepage: https://github.com/nabil6391/flutter_download_manager

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  dio: ^5.0.2
  flutter:
    sdk: flutter
  universal_io: ^2.2.2
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
